name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dotnet build
      run: dotnet build --configuration Release

    - name: Dotnet test
      run: dotnet test

    - name: Typescript install
      run: npm ci
      working-directory: ./DotnetTemplate.Web

    - name: Typescript build
      run: npm run build 
      working-directory: ./DotnetTemplate.Web

    - name: Typescript test
      run: npm run test
      working-directory: ./DotnetTemplate.Web

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: cyberspark13
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: cyberspark13/dotnettemplate
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}